### PR TITLE
Add angular 14 support

### PR DESCRIPTION
**Pull request by rternavskyi**

### CODE REVIEW

**Comment by rternavskyi** [comment]
@AidasK @evilaliv3 @MartinNuc
Hello, could you please check this PR

**Comment by rternavskyi** [comment]
@AidasK @evilaliv3 @MartinNuc @Coly010 @itsaplev
Hello, could you please check this PR

**Comment by AidasK** [comment]
@MartinNuc can you merge this please?

**Comment by MartinNuc** [comment]
@rternavskyi Thank you so much for contribution! I see the pipeline is failing with following error:

```
Error: projects/ngx-flow/src/lib/flow.directive.ts:134:26 - error TS2314: Generic type 'JQueryStyleEventEmitter<TContext, T>' requires 2 type argument(s).
261
262134       flow as unknown as JQueryStyleEventEmitter,
```

I will be happy to merge it when it's 🟢

**Comment by rternavskyi** [comment]
@MartinNuc can you merge this please?

**Comment by MartinNuc** [comment]
@rternavskyi Could you please try `npm run  build`? 🙏 I tried to run it after merging this PR and it's failing. I am no longer working with Angular therefore I am not sure how to debug it. Can you please take a look? 🙏

**Comment by MartinNuc** [comment]
Version 0.6.0 release with support for Angular 14. Thanks @rternavskyi !
